export const FETCH_ROOMS_LIST_REQUEST = 'FETCH_ROOMS_LIST_REQUEST';
export const FETCH_ROOMS_LIST_SUCCESS = 'FETCH_ROOMS_LIST_SUCCESS';
export const FETCH_ROOMS_LIST_FAILURE = 'FETCH_ROOMS_LIST_FAILURE';
